# Generated by Django 6.0 on 2025-12-07 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('country_code', models.CharField(blank=True, max_length=10, null=True)),
                ('total_contacts', models.IntegerField(default=0)),
                ('valid_contacts', models.IntegerField(default=0)),
                ('available_fields', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contact_lists',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='campaign_attachments/')),
                ('attachment_type', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_templates', to=settings.AUTH_USER_MODEL)),
                ('contact_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='whatsappapi.contactlist')),
            ],
            options={
                'db_table': 'campaign_templates',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ModerationIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=255)),
                ('message_text', models.TextField()),
                ('status', models.CharField(choices=[('blocked', 'Blocked'), ('review', 'Requires Review'), ('allowed', 'Allowed')], db_index=True, max_length=20)),
                ('risk_score', models.IntegerField(default=0)),
                ('reasons_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('contact_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_incidents', to='whatsappapi.contactlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Moderation Incident',
                'verbose_name_plural': 'Moderation Incidents',
                'db_table': 'moderation_incidents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserModerationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warnings_count', models.IntegerField(default=0)),
                ('permanently_blocked', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Moderation Profile',
                'verbose_name_plural': 'User Moderation Profiles',
                'db_table': 'user_moderation_profiles',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('fields', models.JSONField(blank=True, default=dict)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_on_whatsapp', models.BooleanField(default=False)),
                ('whatsapp_verified_at', models.DateTimeField(blank=True, null=True)),
                ('custom_field_1', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_field_2', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_field_3', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='whatsappapi.contactlist')),
            ],
            options={
                'db_table': 'contacts',
                'unique_together': {('contact_list', 'phone_number')},
            },
        ),
    ]
