# Generated by Django 6.0 on 2025-12-08 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasendercampaign',
            name='session_phone',
            field=models.CharField(blank=True, help_text='Phone number used for this campaign (preserved after session deletion)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wasendercampaign',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='userpanel.wasendersession'),
        ),
        migrations.AlterField(
            model_name='wasendermessage',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='userpanel.wasendersession'),
        ),
    ]
