# Generated by Django 6.0 on 2025-12-08 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0002_preserve_campaigns_after_session_deletion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OptOutContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=50)),
                ('keyword_used', models.CharField(max_length=50)),
                ('original_message', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('opted_out_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='optout_contacts', to='userpanel.wasendersession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optout_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Opt-Out Contact',
                'verbose_name_plural': 'Opt-Out Contacts',
                'ordering': ['-opted_out_at'],
                'indexes': [models.Index(fields=['user', 'phone_number'], name='userpanel_o_user_id_3b49b9_idx'), models.Index(fields=['phone_number', 'is_active'], name='userpanel_o_phone_n_7fe5c3_idx'), models.Index(fields=['user', 'is_active', 'opted_out_at'], name='userpanel_o_user_id_f6bce3_idx')],
                'unique_together': {('user', 'phone_number')},
            },
        ),
    ]
